### ISSUE TITLE
Data resDATAprepSE  ERROR

### ISSUE THREAD

**Issue by mbmdarkrai** [loubator/MultiRNAflow#3]
I have issues at the first preprocessing stage, the data is uploaded but I get the following error;

> resDATAprepSE <- DATAprepSE(RawCounts=RawCount2,
+                             Column.gene=1,
+                             Group.position=1,
+                             Time.position=2,
+                             Individual.position=3)

Error in ColnamesToFactors(ExprData = dataColToFct, Column.gene = Column.gene,  : 
Every individual must have a unique name, must be associated to a unique group and must be associated only once to each of the same 6 time measurements.

RawCounts2 is data.frame , with NO DUPLICATES in gene column (Esemble ID))
str(RawCount2)
any(duplicated(rownames(RawCount2))) 
any(duplicated(colnames(RawCount2)))

When I run resDATAprepSE with 1 group (group position= NULL) it works fine.
2 groups causes problems

                                              Gene              Cont_t0_r1 Cont_t0_r2 Cont_t0_r3 Cont_t0_r4 
ENSG00000000003 ENSG00000000003       2512       2046       2169       1741       3182
ENSG00000000005 ENSG00000000005         26         31         76         27          0
ENSG00000000419 ENSG00000000419       2065       2774       1944       1878       1596
ENSG00000000457 ENSG00000000457        251        317        302        259        296
ENSG00000000460 ENSG00000000460       1107       1140       1123        927        913
ENSG00000000938 ENSG00000000938         19         14          9          6          0
ENSG00000000971 ENSG00000000971          0          0          0          0          0
ENSG00000001036 ENSG00000001036       2169       2209       2047       1681       1977
ENSG00000001084 ENSG00000001084       2111       2689       2400       1995       1183
ENSG00000001167 ENSG00000001167       1794       1719       1271       1432       1904
ENSG00000001460 ENSG00000001460        223        322        282        276        358
ENSG00000001461 ENSG00000001461        458        524        404        353        311
ENSG00000001497 ENSG00000001497       2497       3325       2546       2298       2650
ENSG00000001561 ENSG00000001561        171        328        341        229        522
ENSG00000001617 ENSG00000001617       1820       1908       1567       1019        854
ENSG00000001626 ENSG00000001626         49         17         52         71          0
ENSG00000001629 ENSG00000001629       2963       3776       2821       2203       2802
ENSG00000001630 ENSG00000001630        202        200        168         80        200
ENSG00000001631 ENSG00000001631        355        473        311        364        520
ENSG00000002016 ENSG00000002016        302        374        293        139       1125
ENSG00000002079 ENSG00000002079          1          1          0          0          0
ENSG00000002330 ENSG00000002330        198        228        228        101        155
ENSG00000002549 ENSG00000002549       1844       2106       1695       1373       1653
ENSG00000002586 ENSG00000002586          4          6         10          5         15
ENSG00000002587 ENSG00000002587          4          1          9          5         14

**Comment by loubator** [comment]
Hi @mbmdarkrai, thank you for using my package.
Based on the error message, I first need to look at colnames of all columns of your dataset before giving an answer.

**Comment by mbmdarkrai** [comment]
Thanks for your reply

 Column names

sample
--
Cont_t0_r1
Cont_t0_r2
Cont_t0_r3
Cont_t0_r4
Cont_t1_r1
Cont_t1_r2
Cont_t1_r3
Cont_t1_r4
Cont_t2_r1
Cont_t2_r2
Cont_t2_r3
Cont_t2_r4
Cont_t3_r1
Cont_t3_r2
Cont_t3_r3
Cont_t3_r4
Cont_t4_r1
Cont_t4_r2
Cont_t4_r3
Cont_t4_r4
Cont_t5_r1
Cont_t5_r2
Cont_t5_r3
Cont_t5_r4
SBMA_t0_r1
SBMA_t0_r2
SBMA_t0_r3
SBMA_t0_r4
SBMA_t1_r1
SBMA_t1_r2
SBMA_t1_r3
SBMA_t1_r4
SBMA_t2_r1
SBMA_t2_r2
SBMA_t2_r3
SBMA_t2_r4
SBMA_t3_r1
SBMA_t3_r2
SBMA_t3_r3
SBMA_t3_r4
SBMA_t4_r1
SBMA_t4_r2
SBMA_t4_r3
SBMA_t4_r4
SBMA_t5_r1
SBMA_t5_r2
SBMA_t5_r3
SBMA_t5_r4


So 2 Groups: Cont and SBMA
4 replicates for each sample
5 time points

My code in R Studio

**# read iin sample**
`counts <- read.delim("iPSC_MutiFlow_Counts.txt", header=T, row.names=1, check.names = T)`

**#filter low counts**
`filtered.counts <- counts[rowSums(counts>= 5) >= 3, ]`

#removesd "na" from data
`dim(filtered.counts)
narows <- apply(filtered.counts, 1, function(x) any(is.na(x)))
table(narows)

countDataClean <- filtered.counts[ !narows, ]
cleancounts <- countDataClean
dim(cleancounts)

**# add Gene column and  move gene ccolum to 1st column**
`RawCounts <- cleancounts

RawCounts$Gene <- row.names(counts_matrix) 

RawCount2 <- RawCounts %>% select(Gene, everything()) 

**# ran data 2 groups with 5 time ponints each, 4 replicates each
# data:  Cont_t0_r1, SBMA_t0_r1**

`resDATAprepSE <- DATAprepSE(RawCounts=RawCount2,
                            Column.gene=1,
                            Group.position=1,
                            Time.position=2,
                            Individual.position=3)`


Thank you!

**Comment by loubator** [comment]
I think I know where the problem is.

The name of replicates must be different if there are different biological conditions. 

Try

Cont_t0_r1
Cont_t0_r2
Cont_t0_r3
Cont_t0_r4
Cont_t1_r1
Cont_t1_r2
Cont_t1_r3
Cont_t1_r4
....
....
SBMA_t0_r5
SBMA_t0_r6
SBMA_t0_r7
SBMA_t0_r8
SBMA_t1_r5
SBMA_t1_r6
SBMA_t1_r7
SBMA_t1_r8

**Comment by mbmdarkrai** [comment]
Thank you so much, your solution worked! 
Your help is much aappreciated.
